language: android
android:
components:
- platform-tools
- tools
- build-tools-21.1.2
- android-21
env:
global:
before_install:
- echo "Before install stage"
install:
- echo "Install stage"
- sudo add-apt-repository -y ppa:chris-lea/node.js
- sudo apt-get update -y
- sudo apt-get install -y nodejs
- npm -g install cordova bower gulp steroids
- npm install
- bower install
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- steroids update
after_success:
- echo "After success stage"
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
on:
tags: true
all_branches: true